#!/bin/bash -xe

# Allows to see errors as they occur
exec 2>&1

echo "Executing init hook"

ln -fs {{pkg.path}}/*.py {{pkg.svc_var_path}}
ln -fs {{pkg.path}}/dags {{pkg.svc_var_path}}

export AIRFLOW_HOME={{pkg.svc_var_path}}

source {{pkg.svc_config_path}}/helpers.sh

create_db_superuser
# set_dir_permissions

echo "Initializing the airflow db..."
exec chpst -U {{cfg.superuser.name}} -u {{cfg.superuser.name}} airflow initdb

echo "Removing airflow examples ..."
python remove_airflow_example.py

echo "Resetting the airflow server ..."
exec chpst -U {{cfg.superuser.name}} -u {{cfg.superuser.name}} airflow resetdb -y

python customize_dashboard.py

