version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
    volumes:
      - ./dags:/usr/src/app/dags
      - ./logs:/usr/src/app/logs
    ports:
      - 8080:8080
